"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { apiCall, downloadCsv, safePrint } from "@/lib/clientApi";
import Toast from "@/components/Toast";

type Tamu = { ID:string; Waktu:string; Tanggal:string; Jam:string; Nama:string; Alamat:string; No_HP:string; Kategori:string; Catatan:string; Petugas:string };

export default function TamuPage(){
  const [rows,setRows]=useState<Tamu[]>([]); const [q,setQ]=useState(""); const [loading,setLoading]=useState(true); const [editing,setEditing]=useState<Tamu|null>(null); const [saving,setSaving]=useState(false); const [toast,setToast]=useState<{m:string;k:"success"|"error"}|null>(null);
  const blank={Nama:"",Alamat:"",No_HP:"",Kategori:"Umum",Catatan:"",Petugas:"Admin"}; const [form,setForm]=useState(blank);
  const load=useCallback(async()=>{const r=await apiCall<Tamu[]>("listTamu"); if(r.ok)setRows(r.data||[]); else setToast({m:r.error||"Gagal memuat data.",k:"error"}); setLoading(false)},[]);
  useEffect(()=>{load(); const id=setInterval(load,5000); return()=>clearInterval(id)},[load]);
  const filtered=useMemo(()=>{const s=q.toLowerCase();return rows.filter(r=>!s||`${r.Nama} ${r.Alamat} ${r.No_HP}`.toLowerCase().includes(s))},[rows,q]);
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);const r=await apiCall(editing?"updateTamu":"addTamu",{...form,ID:editing?.ID});if(r.ok){setToast({m:editing?"Data tamu diperbarui.":"Tamu berhasil ditambahkan.",k:"success"});setForm(blank);setEditing(null);await load()}else setToast({m:r.error||"Gagal menyimpan.",k:"error"});setSaving(false)}
  function edit(r:Tamu){setEditing(r);setForm({Nama:r.Nama,Alamat:r.Alamat,No_HP:r.No_HP,Kategori:r.Kategori||"Umum",Catatan:r.Catatan||"",Petugas:r.Petugas||"Admin"});window.scrollTo({top:0,behavior:"smooth"})}
  async function remove(r:Tamu){if(!confirm(`Hapus tamu ${r.Nama}?`))return;const x=await apiCall("deleteTamu",{ID:r.ID});if(x.ok){setToast({m:"Data tamu dihapus.",k:"success"});load()}else setToast({m:x.error||"Gagal menghapus.",k:"error"})}
  return <div id="admin-tamu-container">{toast&&<Toast message={toast.m} kind={toast.k} onClose={()=>setToast(null)}/>}<div className="admin-page-heading" id="admin-tamu-header"><div><span className="eyebrow">Pendataan kehadiran</span><h1>Buku Tamu</h1><p>Catat tamu dari perangkat mana pun ke database yang sama.</p></div><div className="total-badge" id="tamu-total-badge"><span>Total Tamu</span><strong>{rows.length}</strong></div></div>
  <section className="admin-section-card compact" id="admin-tamu-form-card"><div className="card-heading"><div><h2>{editing?"Edit tamu":"Tambah tamu"}</h2><p>Data dasar tamu yang hadir.</p></div>{editing&&<button id="btn-cancel-edit-tamu" className="btn btn-soft btn-small" onClick={()=>{setEditing(null);setForm(blank)}}>Batal Edit</button>}</div><form id="form-tamu" className="form-grid" onSubmit={submit}><label htmlFor="input-tamu-nama">Nama<input id="input-tamu-nama" required value={form.Nama} onChange={e=>setForm({...form,Nama:e.target.value})}/></label><label htmlFor="input-tamu-alamat">Alamat<input id="input-tamu-alamat" value={form.Alamat} onChange={e=>setForm({...form,Alamat:e.target.value})}/></label><label htmlFor="input-tamu-hp">No. HP<input id="input-tamu-hp" inputMode="tel" value={form.No_HP} onChange={e=>setForm({...form,No_HP:e.target.value})}/></label><label htmlFor="input-tamu-kategori">Kategori<select id="input-tamu-kategori" value={form.Kategori} onChange={e=>setForm({...form,Kategori:e.target.value})}><option>Umum</option><option>Keluarga</option><option>Tetangga</option><option>Teman</option><option>Undangan</option></select></label><label htmlFor="input-tamu-petugas">Petugas<input id="input-tamu-petugas" value={form.Petugas} onChange={e=>setForm({...form,Petugas:e.target.value})}/></label><label htmlFor="input-tamu-catatan">Catatan<input id="input-tamu-catatan" value={form.Catatan} onChange={e=>setForm({...form,Catatan:e.target.value})}/></label><div className="form-actions span-2"><button id="btn-submit-tamu" className="btn btn-primary" disabled={saving}>{saving?"Menyimpan...":editing?"Simpan Perubahan":"Tambah Tamu"}</button></div></form></section>
  <section className="admin-section-card" id="admin-tamu-table-card"><div className="toolbar"><input id="input-search-tamu" className="search-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, alamat, nomor HP..."/><button id="btn-export-tamu" className="btn btn-soft btn-small" onClick={()=>downloadCsv("buku-tamu.csv",rows as unknown as Record<string,unknown>[])}>Export CSV</button><button id="btn-print-tamu" className="btn btn-soft btn-small" onClick={()=>safePrint()}>Print</button></div>{loading?<div className="empty-state">Memuat...</div>:!filtered.length?<div className="empty-state">Belum ada tamu.</div>:<div className="table-wrap"><table><thead><tr><th>Nama</th><th>Alamat</th><th>Kategori</th><th>No. HP</th><th>Waktu</th><th>Aksi</th></tr></thead><tbody>{filtered.map(r=><tr key={r.ID}><td><strong>{r.Nama}</strong><small className="table-sub">{r.Petugas}</small></td><td>{r.Alamat}</td><td>{r.Kategori}</td><td>{r.No_HP}</td><td>{r.Tanggal}<small className="table-sub">{r.Jam}</small></td><td><div className="row-actions"><button id={`btn-edit-tamu-${r.ID}`} onClick={()=>edit(r)}>Edit</button><button id={`btn-del-tamu-${r.ID}`} className="danger-link" onClick={()=>remove(r)}>Hapus</button></div></td></tr>)}</tbody></table></div>}</section></div>
}
