"use client";
import Image from "next/image";
import { useCallback, useEffect, useMemo, useState } from "react";
import PublicHeader from "@/components/PublicHeader";
import Footer from "@/components/Footer";
import { apiCall } from "@/lib/clientApi";
import type { DokumentasiRow } from "@/lib/types";

const cats=["Semua","Persiapan","Acara Utama","Keluarga","Tamu","Panitia","Singa Dangdut","Telitian","Dekorasi","Hiburan","Lainnya"];
export default function GaleriPage(){const[rows,setRows]=useState<DokumentasiRow[]>([]);const[cat,setCat]=useState("Semua");const[active,setActive]=useState<DokumentasiRow|null>(null);const[loading,setLoading]=useState(true);const load=useCallback(async()=>{const r=await apiCall<DokumentasiRow[]>("getPublicGallery");if(r.ok)setRows(r.data||[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);const shown=useMemo(()=>cat==="Semua"?rows:rows.filter(r=>r.Kategori===cat),[rows,cat]);return <><PublicHeader/><main className="page-main container"><div className="page-title"><span className="eyebrow">Momen kebersamaan</span><h1>Galeri Hajatan Gibran</h1><p>Dokumentasi yang telah disetujui panitia akan tampil di sini.</p></div><div className="chip-row">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={cat===c?"chip active":"chip"}>{c}</button>)}</div>{loading?<div className="empty-state big">Memuat galeri...</div>:!shown.length?<div className="empty-state big">Belum ada dokumentasi pada kategori ini.</div>:<div className="gallery-grid">{shown.map(r=><button className="gallery-item" key={r.ID_DOK} onClick={()=>setActive(r)}><Image src={r.Thumbnail_URL||r.Drive_URL} alt={r.Judul||"Dokumentasi Hajatan Gibran"} fill sizes="(max-width: 600px) 50vw, (max-width: 1000px) 33vw, 25vw" unoptimized/><span className="gallery-overlay"><b>{r.Judul||r.Kategori}</b><small>{r.Kategori}</small></span></button>)}</div>}{active&&<div className="lightbox" onClick={()=>setActive(null)}><div className="lightbox-card" onClick={e=>e.stopPropagation()}><button className="lightbox-close" onClick={()=>setActive(null)}>×</button><div className="lightbox-image"><Image src={active.Drive_URL||active.Thumbnail_URL} alt={active.Judul||"Dokumentasi"} fill sizes="90vw" unoptimized/></div><div className="lightbox-copy"><span className="eyebrow">{active.Kategori}</span><h2>{active.Judul||"Dokumentasi Hajatan"}</h2><p>{active.Keterangan}</p><small>Dikirim oleh {active.Nama_Pengirim} • {active.Tanggal}</small></div></div></div>}</main><Footer/></>}
