"use client";
import { ChangeEvent, FormEvent, useState } from "react";
import Image from "next/image";
import PublicHeader from "@/components/PublicHeader";
import Footer from "@/components/Footer";
import { apiCall } from "@/lib/clientApi";

const categories=["Persiapan","Acara Utama","Keluarga","Tamu","Panitia","Singa Dangdut","Telitian","Dekorasi","Hiburan","Lainnya"];

type Prepared={file:File;dataUrl:string;preview:string};

async function compressImage(file:File):Promise<Prepared>{
  if(!["image/jpeg","image/png","image/webp"].includes(file.type)) throw new Error("Format foto harus JPG, PNG, atau WebP.");
  const bitmap=await createImageBitmap(file);const max=1400;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const w=Math.round(bitmap.width*scale),h=Math.round(bitmap.height*scale);const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Browser tidak mendukung kompresi foto.");ctx.drawImage(bitmap,0,0,w,h);bitmap.close();const blob:Blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("Gagal mengompres foto.")),"image/jpeg",0.78));if(blob.size>1_800_000)throw new Error("Foto masih terlalu besar setelah dikompres. Pilih foto lain.");const compressed=new File([blob],file.name.replace(/\.[^.]+$/,"")+".jpg",{type:"image/jpeg"});const dataUrl=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error("Gagal membaca foto."));r.readAsDataURL(compressed)});return{file:compressed,dataUrl,preview:URL.createObjectURL(blob)}}

export default function KirimFotoPage(){const[name,setName]=useState("");const[category,setCategory]=useState("Acara Utama");const[title,setTitle]=useState("");const[desc,setDesc]=useState("");const[files,setFiles]=useState<Prepared[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState<{text:string;ok:boolean}|null>(null);const[progress,setProgress]=useState(0);
async function choose(e:ChangeEvent<HTMLInputElement>){setMessage(null);const selected=Array.from(e.target.files||[]).slice(0,5);try{const output:Prepared[]=[];for(const f of selected)output.push(await compressImage(f));setFiles(output)}catch(err){setMessage({text:err instanceof Error?err.message:"Gagal memproses foto.",ok:false})}}
async function submit(e:FormEvent){e.preventDefault();if(!files.length){setMessage({text:"Pilih minimal satu foto.",ok:false});return}setBusy(true);setProgress(0);let ok=0;for(let i=0;i<files.length;i++){const item=files[i];const r=await apiCall("uploadDocumentation",{Nama_Pengirim:name,Kategori:category,Judul:title,Keterangan:desc,Nama_File:item.file.name,Mime_Type:item.file.type,Data_URL:item.dataUrl});if(r.ok)ok++;setProgress(Math.round(((i+1)/files.length)*100))}if(ok===files.length){setMessage({text:"Terima kasih. Dokumentasi berhasil dikirim dan menunggu persetujuan panitia.",ok:true});files.forEach(f=>URL.revokeObjectURL(f.preview));setFiles([]);setTitle("");setDesc("")}else setMessage({text:`${ok} dari ${files.length} foto berhasil dikirim. Silakan coba ulang foto yang gagal.`,ok:false});setBusy(false)}
return <><PublicHeader/><main className="page-main container upload-page"><div className="page-title"><span className="eyebrow">Bagikan momenmu</span><h1>Kirim Dokumentasi</h1><p>Unggah foto hajatan Gibran. Foto akan diperiksa panitia sebelum tampil di galeri.</p></div><div className="upload-layout"><section className="content-card"><form className="stack-form" onSubmit={submit}><label>Nama Pengirim<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nama Anda"/></label><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Judul Foto<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Contoh: Momen bersama keluarga"/></label><label>Keterangan<textarea rows={3} value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Keterangan singkat (opsional)"/></label><label className="file-drop"><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={choose}/><strong>Pilih Foto</strong><span>Maksimal 5 foto • JPG/PNG/WebP • otomatis dikompres</span></label>{files.length>0&&<div className="preview-grid">{files.map((f,i)=><div className="preview-item" key={f.preview}><Image src={f.preview} alt={`Preview ${i+1}`} fill sizes="150px" unoptimized/><span>{Math.round(f.file.size/1024)} KB</span></div>)}</div>}{busy&&<div className="upload-progress"><div><span style={{width:`${progress}%`}}/></div><small>Mengunggah {progress}%</small></div>}{message&&<div className={message.ok?"notice success":"notice error"}>{message.text}</div>}<button className="btn btn-primary btn-full" disabled={busy}>{busy?"Mengirim Dokumentasi...":"Kirim Dokumentasi"}</button></form></section><aside className="upload-info"><div className="info-bubble">✦</div><h2>Foto Anda ikut menyimpan cerita.</h2><p>Gunakan foto yang pantas untuk dokumentasi keluarga. File akan disimpan di Google Drive milik pengelola acara.</p><ul><li>Foto dikompres agar upload lebih ringan.</li><li>Tidak langsung tampil sebelum disetujui.</li><li>Data tidak bergantung pada satu perangkat.</li></ul></aside></div></main><Footer/></>}
